### ISSUE TITLE
Actividad 2 Entrevista

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-2-entrevista-dinamita#1]
Equipo:
Cruz Cruz Diego
Jiménez Sánchez Irvin
Rosas García Marco Uriel
[Actividad 2 Entrevista.pdf](https://github.com/user-attachments/files/16831371/Actividad.2.Entrevista.pdf)

**Comment by Anakimberly** [comment]
Obtuvieron el 20% ya que cumple con los criterios de la rubrica, desde la preparación de las preguntas hasta el cierre de la entrevista, no presenta ningún error de ortografía y la introducción esta bien redactada

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
